NestedForm/config/routes.rb
Rails.application.routes.draw do
  resources :contact_persones
  resources :customers
  root 'customers#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

NestedForm/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

NestedForm/app/models/contact_persone.rb
class ContactPersone < ApplicationRecord
	belongs_to :customer
	validates :name, presence: true
	def to_s
		name
	end


end

NestedForm/app/models/customer.rb
class Customer < ApplicationRecord
	has_one :contact_persone, dependent: :destroy
	accepts_nested_attributes_for :contact_persone
	validates :name, presence: true

	def to_s
		name
	end

end

NestedForm/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

NestedForm/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @customer.build_contact_persone
    #2.times {@customer.contact_persone.build}
    #@customer.contact_persone.build
  end

  # GET /customers/1/edit
  def edit
    @customer.contact_persone.build
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    #@customer.contact_persone.build

    if @customer.save
      redirect_to @customer
    else
      render 'new'
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, contact_persone_attributes: [:name])
    end
end

NestedForm/app/helpers/application_helper.rb
module ApplicationHelper
end

NestedForm/app/helpers/contact_persones_helper.rb
module ContactPersonesHelper
end

NestedForm/app/helpers/customers_helper.rb
module CustomersHelper
end

NestedForm/app/views/contact_persones/_form.html.erb
<%= form_with(model: contact_persone, local: true) do |form| %>
  <% if contact_persone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact_persone.errors.count, "error") %> prohibited this contact_persone from being saved:</h2>

      <ul>
      <% contact_persone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_persone_name %>
  </div>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id, id: :contact_persone_customer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

NestedForm/app/views/contact_persones/edit.html.erb
<h1>Editing Contact Persone</h1>

<%= render 'form', contact_persone: @contact_persone %>

<%= link_to 'Show', @contact_persone %> |
<%= link_to 'Back', contact_persones_path %>

NestedForm/app/views/contact_persones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contact Persones</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_persones.each do |contact_persone| %>
      <tr>
        <td><%= contact_persone.name %></td>
        <td><%= contact_persone.customer %></td>
        <td><%= link_to 'Show', contact_persone %></td>
        <td><%= link_to 'Edit', edit_contact_persone_path(contact_persone) %></td>
        <td><%= link_to 'Destroy', contact_persone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact Persone', new_contact_persone_path %>

NestedForm/app/views/contact_persones/new.html.erb
<h1>New Contact Persone</h1>

<%= render 'form', contact_persone: @contact_persone %>

<%= link_to 'Back', contact_persones_path %>

NestedForm/app/views/contact_persones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact_persone.name %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @contact_persone.customer %>
</p>

<%= link_to 'Edit', edit_contact_persone_path(@contact_persone) %> |
<%= link_to 'Back', contact_persones_path %>

NestedForm/app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
<% if customer.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

  <ul>
    <% customer.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :name %>
  <%= form.text_field :name, id: :customer_name %>
</div>

<h2>Contact Persone</h2>
<%= form.fields_for :contact_persone, customer.contact_persone do |builder| %>
  <%= builder.label :name %>
  <%= builder.text_field :name %>
  <br> <br>
<% end %>
<div class="actions">
  <%= form.submit %>
</div>
<% end %>

NestedForm/app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

NestedForm/app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

NestedForm/app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

NestedForm/app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

NestedForm/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedForm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>