FormDemo/config/routes.rb
Rails.application.routes.draw do
 
 resources :tables
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

FormDemo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

FormDemo/app/models/person.rb
class Person < ApplicationRecord
	belongs_to :table
	validates :name, presence: true

	def to_s
		name
	end
end

FormDemo/app/models/table.rb
class Table < ApplicationRecord
	has_one :person, dependent: :destroy
	accepts_nested_attributes_for :person
	validates :name, presence: true

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	def to_s
		name
	end
end

FormDemo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

FormDemo/app/controllers/tables_controller.rb
class TablesController < ApplicationController
	def index
		@tables = Table.all
	end

	def show
		@table = Table.find(params[:id])
  	end
	
	def new
		@table = Table.new
		@table.build_person
		#1.times {@table.person.build}
	end

	def create
		@table = Table.create(table_params)

		#1.times {@table.person.build}
		if @table.save
			flash[:notice] = "Thank you for your submission..."
			redirect_to @table
		else
			render 'new'
		end
	end
	def table_params
		params.require(:table).permit(:name, :avatar, person_attributes: [:name, :contact])
	end
end

FormDemo/app/helpers/application_helper.rb
module ApplicationHelper
end

FormDemo/app/helpers/tables_helper.rb
module TablesHelper
end

FormDemo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

FormDemo/app/views/tables/_form.html.erb
<%= form_for @table, url: tables_path, html: { multipart: true } do |form| %>
<p>
	<%= form.label :name %>
	<%= form.text_field :name %>
	<%= form.file_field :avatar %>
</p>
<br>
<h3>Person for table</h3>
	<%= form.fields_for :person do |f| %>
		<%= f.label :name %>
        <%= f.text_field :name %>
 		<br><br>
        <%= f.label :contact %>
        <%= f.text_field :contact %>
        
	<% end %><br><br>
<%= form.submit "Submit" %>
<% end %>

FormDemo/app/views/tables/create.html.erb
<h1>Tables#create</h1>
<p>Find me in app/views/tables/create.html.erb</p>

FormDemo/app/views/tables/index.html.erb
<h1>Tables#index</h1>

FormDemo/app/views/tables/new.html.erb
<h2>Table#new</h2>
<%= render "form" %>

FormDemo/app/views/tables/show.html.erb
<h2>Show</h2>
<%#= image_tag @table.avatar.url(:medium) %>


<%= @table.name %><br>
<%= @table.person.name %><br>
<%= @table.person.contact %><br>
<%= image_tag @table.avatar.url(:medium) %>